### ISSUE TITLE
Update packages and supported ink! version

### ISSUE THREAD

**Issue by codespool** [AstarNetwork/swanky-cli#109]
# Overview (What and Why)

Dependencies and supported ink! version need to be updated to keep swanky-cli compatible with ecosystem changes

# How

- [x] ink! to v4
- [x] all polkadotjs dependencies
- [x] oclif package
- [x] swanky node to v1.1.0
- [x] cargo-contract to 2.X (only applies to dev container and docs)

# Definition of Done

- [x] Packages updated and a new version of swanky-cli released to npm and Github
- [x] Dev container template updated to use the new version
- [ ] docs updated

**Comment by codespool** [comment]
After this is done, the dev container also needs to be updated:
https://github.com/AstarNetwork/swanky-dev-container/issues/3

**Comment by codespool** [comment]
Everything is reviewed and merged, except the docs part, which is still in review.

Once that is merged, this can be closed.

https://github.com/AstarNetwork/astar-docs/pull/307

**Comment by shunsukew** [comment]
The doc part is merged, let's close this issue.
