### ISSUE TITLE
`contract compile` should compile all contracts by default

### ISSUE THREAD

**Issue by codespool** [AstarNetwork/swanky-cli#110]
# Overview (What and Why)

If there are multiple contracts, thy are mostly gonna be a part of the same project, and therefore should all be compiled with `swanky contract compile` command. 

Compiling individual contracts should still be possible by passing the contract name flag

# How

- [ ] modify contract compile command
  - [ ] remove required arg
  - [ ] add contract name flag to take one or more contract names
- [ ] queue all existing contracts or those specified and compile them in series
(not much would be gained by compiling in parallel threads since the compiler already uses them) 
- [ ] extract the core of `test` command into a function and call it for all contracts
# Definition of Done

- [ ] above changes are implemented and merged
- [ ] readme page and docs.astar page are updated

# Open Issues and Blockers

**Comment by shunsukew** [comment]
`swanky contract test` should also have the same functionality.
This is part of requirements for e2e CI test

**Comment by codespool** [comment]
Updated
