### ISSUE TITLE
[BUG] swanky contract compile throws Error if no contract name specified

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#128]
**Description**

I have run the command within a flipper generated project folder (only one contract inside) and I get the error `Error: Cannot find contract info for undefined contract in swanky.config.json`

**Expected vs. Actual Behavior**

Based on release notes for Swanky CLI v2.1.0 command `swanky contract compile` invoked in project folder without naming the contract should compile all contracts in the folder.

**Steps to Reproduce** +  **Environment** + **Logs, Errors or Screenshots** 

Output of commands can be seen in the screenshot attached:
```
  swanky contract compile
  swanky --version
  swanky check
  swanky contract compile
  swanky contract compile flipper
```

![image](https://user-images.githubusercontent.com/95318860/225873340-33edc9ae-0d18-4513-8017-18c528683186.png)

**Comment by shunsukew** [comment]
As explained here https://github.com/AstarNetwork/swanky-cli/pull/129#discussion_r1140154837
Close this issue.
