### ISSUE TITLE
TS scripts framework

### ISSUE THREAD

**Issue by shunsukew** [AstarNetwork/swanky-cli#134]
Each contract will have TS deployment script by default, and executable by swanky command for e.g. `swanky contract (script) run`.

Users can arbitrary TS scripts under `scripts` folder and automate deployments and other repetitive operations by writing codes.

https://github.com/AstarNetwork/swanky-cli/issues/112#issuecomment-1486075149

Similar to what [truffle](https://next-stack.github.io/docs/getting_started/scripts)/hardhat has.

**Comment by codespool** [comment]
`execa` now has a scripts feature, which we can leverage for this: https://github.com/sindresorhus/execa/blob/main/docs/scripts.md

Closing this for now, and will create a new ticket with execa.
