### ISSUE TITLE
Nothing happened when trying to compile

### ISSUE THREAD

**Issue by sirius651** [AstarNetwork/swanky-cli#19]
Version:   @astar-network/swanky-cli/0.2.0 darwin-x64 node-v16.15.1

after 
```
$ swanky init testproj
```

choose `flipper`
 
```
$ swanky contract compile flipper
```

Nothing happened and just show message as 
`✔ Contract compiled successfully`

**Comment by codespool** [comment]
Hi @sirius651 , thanks for reporting.
Can you double check a few things:
1) are you located in the actual project folder (missing step between `init` and `compile` is `cd proj_dir`)
2) you have rust, `cargo`, and `cargo contract` installed

**Comment by sirius651** [comment]
1. yes.
2. I think `cargo contract` is missing. should I install this on my local system or any docker image including pre-requirements?

**Comment by codespool** [comment]
I'm not aware of such an image, but it should be fairly easy to install:
https://github.com/paritytech/cargo-contract

Btw, running `swanky check` should warn you about those issues (an issue was discovered recently concerning contract ink! versions, but it should work for detecting the basic dependencies like `cargo contract`)
