### ISSUE TITLE
ModuleLoadError: [MODULE_NOT_FOUND] require failed to load

### ISSUE THREAD

**Issue by TomaszWaszczyk** [AstarNetwork/swanky-cli#20]
I got following error on Linux machine:

> ModuleLoadError: [MODULE_NOT_FOUND] require failed to load

[swanky.webm](https://user-images.githubusercontent.com/1605705/194335486-918baa23-9ff4-4f2b-8806-a84ff977a7b7.webm)

```
tomek@rhei-box:~/workspaces/ink$ node --version
v14.17.6
tomek@rhei-box:~/workspaces/ink$ npm --version
8.19.2
```

On Windows machine works, although many developers use another OS than Windows.

**Comment by codespool** [comment]
Hi @TomaszWaszczyk , thanks for reporting!

I don't think it's an OS issue, but node version. 
You use v14, and it doesn't support native module import syntax (`node:path`).
Since you're using nvm, it should be trivial to add the latest node version and use it.

**Comment by TomaszWaszczyk** [comment]
Thanks, right, I confirm that on NodeJS `v18.10.0` version all works like a charm!

![image](https://user-images.githubusercontent.com/1605705/195081284-05b9c07b-5dac-4968-9b7f-4e8f8d47ec50.png)
