### ISSUE TITLE
CLI shows contract compiled successfully while it's not

### ISSUE THREAD

**Issue by PierreOssun** [AstarNetwork/swanky-cli#24]
When I compile a contract, even though there is an error during compilation, swanky tells me it went successfully.
![Screenshot from 2022-10-13 14-32-18](https://user-images.githubusercontent.com/35110271/195596907-91a80e1a-c4d8-40dc-b3d3-12f437839364.png)

**Comment by codespool** [comment]
Fixed in https://github.com/AstarNetwork/swanky-cli/pull/32
