### ISSUE TITLE
Template for package.json should be changed.

### ISSUE THREAD

**Issue by Naokiakazawa** [AstarNetwork/swanky-cli#26]
package.json generated after `swanky init` would be wrong.
I think package.json.tpl should be changed as follow. (object of `scripts` key)

```
{
,,,,
  "scripts": {
    ,,,,
    "compile": "swanky contract compile",
    "deploy": "swanky contract deploy"
  },
,,,
}
```

Is this a template matter?

**Comment by shunsukew** [comment]
Thank you so much for pointing out.
Forgot to update with this PR https://github.com/AstarNetwork/swanky-cli/pull/14
