### ISSUE TITLE
Node download percentage during `init` should be limited to 2 decimals.

### ISSUE THREAD

**Issue by codespool** [AstarNetwork/swanky-cli#37]
During `Downloading node` phase of init command, the download percentage is displayed using too many digits, should be limited to 2.

**Comment by nuboh8** [comment]
Would it be a change like this on line 98 of (**/workspaces/swanky-cli/packages/core/src/lib/tasks.ts**) where the number (event.progress) is rounded to two decimals?

![image](https://user-images.githubusercontent.com/44810802/211908374-2b639153-7ebe-454c-946a-a08a2289516c.png)

**Comment by nuboh8** [comment]
It would. So we should avoid conversion and focus on the type? It's currently displaying more then it should for a progress percentage bar.

**Comment by codespool** [comment]
No conversion is necessary because the `event.progress` is already a number. Otherwise, what you suggested is correct.

**Comment by nuboh8** [comment]
Okay. Removing the unnecessary number conversion in **Number(event.progress).toFixed(2)**, the solution should be **event.progress.toFixed(2)**

**Comment by shunsukew** [comment]
closed by https://github.com/AstarNetwork/swanky-cli/pull/80
