### ISSUE TITLE
Error:"timed out" is occurred by using Command "swanky compile".

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/swanky-cli#4]
Hi. I have a problem about "swanky compile".
Any settings which I have to do?

<img width="541" alt="image" src="https://user-images.githubusercontent.com/38233656/180666280-b7ce5df3-7011-4dcf-aaaf-6121a07e6853.png">

**Comment by codespool** [comment]
Not sure where the timeout is coming from, can you manually run
`cargo +nightly contract build` from inside `testProject/contracts/CONTRACT_NAME` and see if the timeout happens again?

**Comment by realtakahashi** [comment]
I could compile in the contract directory without time out.
```
shin.takahashi@shintakahashinoMacBook-Pro flipper % pwd
/Users/shin.takahashi/develop/swanky/testProject/contracts/flipper
shin.takahashi@shintakahashinoMacBook-Pro flipper % cargo +nightly contract build
 [1/5] Checking ink! linting rules
Checking with toolchain `nightly-2022-03-14-x86_64-apple-darwin`
   Compiling secp256k1-sys v0.5.2
    Checking libc v0.2.126
   Compiling quote v1.0.20
-- snip --
   Compiling swanky_contract v0.1.0 (/private/var/folders/ft/fdfzmmz129lb72kygrn257gh0000gn/T/cargo-contract_SyCjkf)
   Compiling metadata-gen v0.1.0 (/private/var/folders/ft/fdfzmmz129lb72kygrn257gh0000gn/T/cargo-contract_SyCjkf/.ink/metadata_gen)
    Finished release [optimized] target(s) in 1m 14s
     Running `target/ink/release/metadata-gen ''`
 [5/5] Generating bundle

Original wasm size: 48.6K, Optimized: 22.7K

The contract was built in DEBUG mode.

Your contract artifacts are ready. You can find them in:
/Users/shin.takahashi/develop/swanky/testProject/contracts/flipper/target/ink

  - swanky_contract.contract (code + metadata)
  - swanky_contract.wasm (the contract's code)
  - metadata.json (the contract's metadata)
```

**Comment by codespool** [comment]
I've traced the issue to @oclif/core dependency: https://github.com/oclif/core/issues/453
..and made a new build using the version before the issue was introduced:

[@astar-network/swanky-cli@0.1.4
](https://www.npmjs.com/package/@astar-network/swanky-cli/v/0.1.4)

Please give it a try!

**Comment by realtakahashi** [comment]
Thank you for your helping!

But I could not install swanky@0.1.4.
Would you help me how install swanky@0.1.4?

<img width="820" alt="image" src="https://user-images.githubusercontent.com/38233656/180878844-3a93cc9b-f5c1-4226-9c07-972c5df606e3.png">

**Comment by codespool** [comment]
oh, that's interesting 🤔 
Can you try `npm i -g @astar-network/swanky-cli@latest`

**Comment by realtakahashi** [comment]
The version "0.1.3" has be installed when I used the command that is "swanky-cli@latest".

<img width="628" alt="image" src="https://user-images.githubusercontent.com/38233656/180981552-5ba6c6b4-c691-45ff-b201-34a51c487399.png">

**Comment by codespool** [comment]
Only thing that comes to mind is trying `npm cache clean --force`

**Comment by realtakahashi** [comment]
Great! Great! Great!
Thanks to you, this problem has been resolved.

I think the WASM integrated environment "swanky" project is a great project!
I will support you!

<img width="882" alt="image" src="https://user-images.githubusercontent.com/38233656/181008371-93f8c81c-b223-4344-8a77-65e1c954e267.png">

**Comment by codespool** [comment]
Great that it's resolved, thank you for the kind words! 😁 
Happy building!
