### ISSUE TITLE
Psp22 template cannot be compiled.

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/swanky-cli#45]
I have the following problem:
1. The struct definition does not have the correct name.
2. Your openbrush definition doesn't match Cargo.toml.

swanky version:
```
% swanky --version
@astar-network/swanky-cli/1.0.0-beta.4 darwin-x64 node-v16.4.0
```

**Comment by codespool** [comment]
Hi! 
There's been a couple of updates since beta.4.
Could you try with 1.0.0-rc.4 and see what happens?
(also, clearing the npm/yarn cache might be helpful as well)
