### ISSUE TITLE
psp22 template test run gives error

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/swanky-cli#49]
- my os
```
13.0.1（22A400）
```
- version
```
@astar-network/swanky-cli/1.0.0-rc.4 darwin-x64 node-v18.0.0
```
- The "swanky contract test psp22" command fails, but the "npm test" command succeeds. I think it's a configuration issue, but currently I don't know how to solve it.

<img width="860" alt="image" src="https://user-images.githubusercontent.com/38233656/205482606-0440c05a-c8c8-4a68-9099-c53af0c5c7fd.png">

**Comment by codespool** [comment]
You're right, the test command doesn't work atm, and it should be removed until it's functional.
npm/yarn test is the way to go for now.

I assume this also means #45 is also resolved then.
