### ISSUE TITLE
Getting error if yarn is not installed

### ISSUE THREAD

**Issue by shunsukew** [AstarNetwork/swanky-cli#57]
Getting below error with init command when not having yarn locally.
<img width="1353" alt="Screen Shot 2022-12-20 at 16 33 19" src="https://user-images.githubusercontent.com/28953860/208609224-15f777b0-0b39-49fa-966e-12ceabc39e6f.png">

Showing success message when having error is also problematic

**Comment by codespool** [comment]
Ah, it actually succeeds, switching to npm when `yarn --version` fails.
Outputting the error is a problem though.
Made a quick fix: #108
