### ISSUE TITLE
Improve Contract Interaction

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#63]
# Overview (What and Why)

This is a collection of smaller fixes and improvements to contract interaction.

- Deploy
    - Should either detect, or take as argument the constructor name #35 https://github.com/AstarNetwork/swanky-cli/pull/77
    ~~- Multi contract deploy:~~
      ~~- allow more than one contract to be listed in the deploy command and deploy them sequentially~~
- Compile
    - support `—-release` flag https://github.com/AstarNetwork/swanky-cli/pull/76
    ~~- running typechain complier inside Swanky -~~
      ~~- consider Sumi as alternative parser~~
      ~~- TODO @PierreOssun elaborate feature here (from your perspective)~~
- Call
    - dynamically add command and argument options (either from prebuilt types, or on-the-fly) and verify them before making the call https://github.com/AstarNetwork/swanky-cli/pull/98
- Node
  -  pass CORS whitelist as a param and config property #74 https://github.com/AstarNetwork/swanky-cli/pull/78
- General:
  - centralised error handling (see comment), also takes care of #57 

# How
{Describe what needs to be done.}

- [x]  Constructor arguments
- [ ] ~Multi-contract deploy~
- [x] Release flag on compile
- [x] command name options from compiled types
- [x] CORS whitelist as a param and config prop
- [ ] Error handling

Typechain compiler and alternatives is an investigation task, and if implementation needed will be moved to a separate ticket.

# Definition of Done

- [ ]  above features implemented and merged

# Open Issues and Blockers

**Comment by codespool** [comment]
This should also include improved error handling.
All error handling should be centralised, and errors standardised. (considering: https://github.com/ehmicky/modern-errors)

**Comment by shunsukew** [comment]
```
Multi contract deploy:
allow more than one contract to be listed in the deploy command and deploy them sequentially
```
What is the benefit of this? Each contracts has different constructor and gas required to deploy. And network to deploy is not necessary the same for all contracts. This makes deploy command complicated.
I'd suggest script framework instead which can automate frequently used operations (including multi contracts deployment).

**Comment by codespool** [comment]
extracting the `error handling` part and closing this.
