### ISSUE TITLE
 Import Existing Project

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#64]
# Overview (What and Why)

Implement feature to import smart contract from local or remote repo (no need for template).
While importing perform check dir structure, and update configs.

# How

- [ ] Read a project (ink! or ask! from local drive)
- [ ] Read a project from remote repo
- [ ] Prompt user to confirm files to be copied and config to be updated
- [ ] Copy and update config
- [ ] Warn the user of probability that some paths and parameters need to be updated manually

# Definition of Done

- [ ] Possible to import ink! contract from local drive or remote repo
- [ ] Possible to import ask! contract from local drive or remote repo

# Open Issues and Blockers

**Comment by codespool** [comment]
- should read `cargo.toml` to detect workspaces
- build all contracts from that cargo.toml
- use shell script to "build all" (with cargo contact)

**Comment by codespool** [comment]
retiring this in favour of #111
