### ISSUE TITLE
Installers/Distribution

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#65]
# Overview (What and Why)

Why: Current flow is download, extract, and link to /usr/local/bin. It is not user friendly.

What: Implement a user friendly way to auto update the tool is needed.

Idea:
    - worth considering packing as .pkg, or .deb (certificate needed)
    - also, look into brew, apt distribution

# How

- [ ] Investigate distribution options
- [ ] Produce an analysis doc

# Definition of Done
{Write definition of done, how to verify}

- [ ] Analysis document with recommended distribution modes published

# Open Issues and Blockers

**Comment by codespool** [comment]
needs investigation, lower prio

**Comment by codespool** [comment]
With npm now working properly (after ESM update in v3), and the dev container image configured, additional distribution channels would introduce unnecessary overhead. Closing.
