### ISSUE TITLE
Ask project scaffolding: more templates

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#68]
# Overview (What and Why)

- Why: make dev reach bigger, position Astar as de facto Ask Network
- What: all templates translated to Ask. Showcases translated to Ask.
- Missing feature
    - typechain integration
    - unified flow with Ink! and Ask

# How
{Describe what needs to be done.}

- [ ]  Task 1
- [ ]  Task 2

# Definition of Done
{Write definition of done, how to verify}

- [ ]  Unit test cases (delete if not applicable)
- [ ]  Docs updated (delete if not applicable)
- [ ]  PR approved and merged to master (delete if not applicable)

# Open Issues and Blockers
{Dependencies issue or PR or some other blocker.}

**Comment by codespool** [comment]
needs https://github.com/AstarNetwork/swanky-cli/issues/69
Will leave for next sprint

**Comment by codespool** [comment]
closing since we're not supporting ask! atm.
