### ISSUE TITLE
PSP22 reference implementation in Ask

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#69]
# Overview (What and Why)

At the moment, ask! option in Swanky only offers ERC20 template.
To be consistent with ink!, and compliant with standards, this should be PSP22, possibly other standards too.

Since those standards are a collection of contracts, a builder page would be a good idea.
(see https://openbrush.io/)

# How

[ ] Create Openbrush equivalent contracts in ask!
[ ] Create a webapp to combine the contracts (same as openbrush.io)
[ ] Write an ask! tutorial on Astar docs page

[optional: check with Brushfam would they be willing to host it together with ink!]
 
# Definition of Done

- [ ] ask! contracts available on github
- [ ] builder page deployed
- [ ] Tutorial page published on Astar docs

# Open Issues and Blockers

- check is there a way to enforce the function selector as in psp22 (check the compiled blob)

**Comment by codespool** [comment]
- check is there a way to enforce the function selector as in psp22 (check the compiled blob)

**Comment by andabak** [comment]
Removing from this iteration as ask! is not mature enough at this point in time.
