### ISSUE TITLE
Using Swanky CLI to manage existing dApp projects 

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/swanky-cli#70]
# Overview (What and Why)
{Write description of what the feature should be, why}

- Build on top of https://github.com/AstarNetwork/swanky-cli/issues/62
- Open issue: passing the right path to contract folder
- TODO - describe feature from end user perspective

# How
{Describe what needs to be done.}

- [ ]  Task 1
- [ ]  Task 2

# Definition of Done
{Write definition of done, how to verify}

- [ ]  Unit test cases (delete if not applicable)
- [ ]  Docs updated (delete if not applicable)
- [ ]  PR approved and merged to master (delete if not applicable)

# Open Issues and Blockers
{Dependencies issue or PR or some other blocker.}

**Comment by codespool** [comment]
deprecated in favour of https://github.com/AstarNetwork/swanky-cli/issues/64
