### ISSUE TITLE
[BUG] The contract which did not specify with parameter are compiled

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/swanky-cli#75]
**Description**
The contract which did not specify with parameter are compiled

**Steps to Reproduce**
- I created two contracts with "swanky contract new <contract name>". I call contracts in this issue like that, One is A contract, another is B contract.
- A contract have compile errors.
- B contract can be compiled. 
- When I execute command "swanky contract compile <B contract>, I got errors about <A contract>

**Expected vs. Actual Behavior**
When I execute command "swanky contract compile <B contract>, I got errors about <A contract>

**Environment**

- Operating system: mac os 13.1（22C65）
- Project version/tag: swanky 1.0.7
- Rust version : 
```
Default host: x86_64-apple-darwin
rustup home:  /Users/shin.takahashi/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2020-04-06-x86_64-apple-darwin
nightly-2022-03-14-x86_64-apple-darwin
nightly-2022-06-30-x86_64-apple-darwin
nightly-2022-08-15-x86_64-apple-darwin
nightly-2022-10-10-x86_64-apple-darwin
nightly-2022-10-25-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.51.0-x86_64-apple-darwin
1.61.0-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.66.0 (69f9c33d7 2022-12-12)
```
- Node version : v18.2.0

**Comment by shunsukew** [comment]
This is known issue which comes from [typechain-compiler](https://github.com/Supercolony-net/typechain-polkadot#usage-of-typechain-compiler)'s limitation.
https://github.com/AstarNetwork/swanky-cli/tree/master/packages/cli#notes-and-known-issues

We will release dirty fix as a short term solution soon this week.
