### ISSUE TITLE
[BUG] generated js test file with template name instead of custom smart contract name

### ISSUE THREAD

**Issue by kziemianek** [AstarNetwork/swanky-cli#85]
**Description**

After generating new smart contract environment with smart contract based on flipper template but with different name <my-contract-name>, the generated js test file is still named `flipper.test.ts` instead of `<my-contract-name>.test.js`

**Expected vs. Actual Behavior**

To have js test filed named as generated smart contract, ex: `<my-contract-name>.test.js`

**Environment**

- Operating system: macos
- Project version/tag: @astar-network/swanky-cli/1.0.10 darwin-x64 node-v18.2.0

**Logs, Errors or Screenshots**

```
kziemianek@Kaspers-MBP foobar % pwd
/Users/kziemianek/projects/astar/foobar/test/foobar
kziemianek@Kaspers-MBP foobar % ls -ltr
total 8
-rw-r--r--  1 kziemianek  staff  1525 Feb  2 09:57 flipper.test.ts
```

**Comment by kziemianek** [comment]
@codespool, @shunsukew what do you think about just renaming all templates containing tests to `index.test.ts.hbs` so no renaming during templates processing will be needed ? These test files are already in smart contract context (`/test/<my-contract-name>/index.ts`)

**Comment by codespool** [comment]
Actually, a great idea!
(sorry, for the late reply btw)
Since template only holds a sample, and all the test command picks up everything ending in `.test.ts`, this will simplify the init process.
