### ISSUE TITLE
Can't use precompiled binaries in M1 apple chip Macbook

### ISSUE THREAD

**Issue by ganesh1233456** [AstarNetwork/swanky-cli#88]
None of those [archive](https://github.com/AstarNetwork/swanky-cli/releases/tag/v1.0.10) work for `M1 Apple chip Macbook`.  I have followed instruction from [here](https://docs.astar.network/docs/wasm/sc-dev/swanky#recommended-way-downloading-the-precompiled-binaries). But while setting they all give same issue which is `cannot be opened because it is from an unidentified developer`

**Comment by codespool** [comment]
Hey @123oli , that's probably not to do with platform, but with permissions.
Try opening the location of `swanky` executable in finder, right clicking and choosing `open`, and in the popup dialog choose "open" again.
It should run once in the terminal app, and then you'd be able to use it from your cli.

**Comment by 123oli** [comment]
@codespool  While using `swanky --version` command, it show `@astar-network/swanky-cli/1.0.10 darwin-x64 node-v18.2.0` which means swanky installed successfully. But when creating swanky project with command `swanky init flipper` it throws `Cannot find module 'tslib'` error and I installed with `npm install tslib --force` and successfully install but still not working.

<img width="1440" alt="Screenshot 2023-02-03 at 08 50 44" src="https://user-images.githubusercontent.com/42571338/216503257-a5ad8b4d-eb76-45aa-ae42-f9b0c7f44313.png">

**Comment by 123oli** [comment]
@codespool with right clicking and choose open then `cannot execute binary file` error message display. Why this?

<img width="1440" alt="Screenshot 2023-02-03 at 10 49 30" src="https://user-images.githubusercontent.com/42571338/216516904-ff1827b3-a489-4943-af27-f7cc7bdeb712.png">

**Comment by shunsukew** [comment]
I'm using M1 mac and everything works fine. I haven't checked deeply but it's because Rosetta is not installed?
Basically mac artifacts are targeting Intel x86_64 architecture, M1 mac (aarch64) users need to install Rosetta to be compatible with x86_64 programs.

**Comment by ganesh1233456** [comment]
> I'm using M1 mac and everything works fine. I haven't checked deeply but it's because Rosetta is not installed? Basically mac artifacts are targeting Intel x86_64 architecture, M1 mac (aarch64) users need to install Rosetta to be compatible with x86_64.

@shunsukew thanks after installing rosetta it works :)
